import "./globals.css";
import { Rubik } from "next/font/google";

/* context */
import { CounterContextProvider } from "@/context/counter";
import DarkModeProvider from "@/context/darkmode";

/* clerk */
import { ClerkProvider } from "@clerk/nextjs";

/* nextauth */
import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Ninja Helpdesk",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      {/* suppressHydrationWarning={true} is used to suppress Extra attributes from the server: cz-shortcut-listen */}
      <body className={rubik.className} suppressHydrationWarning={true}>
        <DarkModeProvider>
          {/* <SessionProvider session={session}> */}
          {/* <ClerkProvider> */}
          <CounterContextProvider>
            {children}
          </CounterContextProvider>
          {/* </ClerkProvider> */}
          {/* </SessionProvider> */}
        </DarkModeProvider>
      </body>
    </html>
  );
}
