import { Rubik } from 'next/font/google'
import './globals.css'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Ninja Helpdesk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning={true} is used to suppress Extra attributes from the server: cz-shortcut-listen */}
      <body className={rubik.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}
